apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: credits-service
  labels:
    app: credits-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credits-service
  template:
    metadata:
      labels:
        app: credits-service
    spec:
      imagePullSecrets:
        - name: docker-keix
      containers:
        - args:
            - node
            - service/credits/run.js
        - env:
            - name: HOST
              value: "message-store.default.svc.cluster.local:8080"
          name: credits-service
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
